"""init five tables

Revision ID: 0001_init
Revises: 
Create Date: 2026-07-30 00:27:01.282719
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_init'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('risk_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('OPERATOR', 'USER', 'VERIFIER', 'ADMIN')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_invocations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('parsed_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('degraded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('degrade_reason', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('RECOMMEND', 'RISK')", name='ck_ai_invocations_purpose'),
    sa.CheckConstraint('degraded = false OR degrade_reason IS NOT NULL', name='ck_ai_invocations_degrade_reason'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_invocations_purpose_created', 'ai_invocations', ['purpose', 'created_at'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_stock', sa.Integer(), nullable=False),
    sa.Column('claimed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validity_minutes', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('FOOD', 'TRAVEL', 'SHOPPING', 'LIFE')", name='ck_campaigns_category'),
    sa.CheckConstraint('claimed_count <= total_stock', name='ck_campaigns_no_oversell'),
    sa.CheckConstraint('claimed_count >= 0', name='ck_campaigns_claimed_count_non_negative'),
    sa.CheckConstraint('end_at > start_at', name='ck_campaigns_time_window'),
    sa.CheckConstraint('face_value > 0', name='ck_campaigns_face_value_positive'),
    sa.CheckConstraint('per_user_limit >= 1', name='ck_campaigns_per_user_limit_min'),
    sa.CheckConstraint('total_stock > 0', name='ck_campaigns_total_stock_positive'),
    sa.CheckConstraint('validity_minutes >= 1', name='ck_campaigns_validity_minutes_min'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_category', 'campaigns', ['category'], unique=False)
    op.create_index('ix_campaigns_window', 'campaigns', ['start_at', 'end_at'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('window_request_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=8), nullable=False),
    sa.Column('degraded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ai_invocation_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('handled_by', sa.BigInteger(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decided_by IN ('RULE', 'AI')", name='ck_risk_events_decided_by'),
    sa.CheckConstraint("decision IN ('PASS', 'BLOCK', 'MANUAL_REVIEW')", name='ck_risk_events_decision'),
    sa.CheckConstraint("status IN ('PENDING', 'RELEASED', 'KEPT')", name='ck_risk_events_status'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='ck_risk_events_score_range'),
    sa.ForeignKeyConstraint(['ai_invocation_id'], ['ai_invocations.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_events_created_at', 'risk_events', ['created_at'], unique=False)
    op.create_index('ix_risk_events_status', 'risk_events', ['status'], unique=False)
    op.create_index('ix_risk_events_user_created', 'risk_events', ['user_id', 'created_at'], unique=False)
    op.create_table('user_coupons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=8), server_default='UNUSED', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("(status = 'USED' AND used_at IS NOT NULL AND used_by IS NOT NULL) OR (status = 'UNUSED' AND used_at IS NULL AND used_by IS NULL)", name='ck_user_coupons_used_consistency'),
    sa.CheckConstraint("status IN ('UNUSED', 'USED')", name='ck_user_coupons_status'),
    sa.CheckConstraint('seq >= 1', name='ck_user_coupons_seq_min'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', 'seq', name='uq_user_coupons_campaign_user_seq'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_user_coupons_campaign_status', 'user_coupons', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_user_coupons_user_claimed_at', 'user_coupons', ['user_id', 'claimed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_coupons_user_claimed_at', table_name='user_coupons')
    op.drop_index('ix_user_coupons_campaign_status', table_name='user_coupons')
    op.drop_table('user_coupons')
    op.drop_index('ix_risk_events_user_created', table_name='risk_events')
    op.drop_index('ix_risk_events_status', table_name='risk_events')
    op.drop_index('ix_risk_events_created_at', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index('ix_campaigns_window', table_name='campaigns')
    op.drop_index('ix_campaigns_category', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_ai_invocations_purpose_created', table_name='ai_invocations')
    op.drop_table('ai_invocations')
    op.drop_table('users')
    # ### end Alembic commands ###
